// <auto-generated />
using System;
using IntranetDocumentos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntranetDocumentos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250621000000_AddDocumentDownloadAnalytics")]
    partial class AddDocumentDownloadAnalytics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is a simplified version - EF Core will regenerate the complete model
        }
    }
}
