name: Build and Deploy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore
        run: dotnet restore app_public.sln
      - name: Build
        run: dotnet build app_public.sln --no-restore --configuration Release
      - name: Test
        run: dotnet test app_public.sln --no-build --verbosity normal --configuration Release
        continue-on-error: true
      - name: Publish
        run: dotnet publish app_public.sln --no-build --configuration Release --output ./publish
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./publish/
          retention-days: 30

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./deployment
      - name: Deploy to Development
        run: |
          echo "Deploying to development environment..."
          ls -la ./deployment
