name: Build and Deploy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore
        run: dotnet restore IntranetDocumentos.csproj
      - name: Build
        run: dotnet build IntranetDocumentos.csproj --no-restore --configuration Release
      - name: Test
        run: dotnet test IntranetDocumentos.csproj --no-build --verbosity normal --configuration Release
        continue-on-error: true
      - name: Publish
        run: dotnet publish IntranetDocumentos.csproj --no-build --configuration Release --output ./publish
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./publish/
          retention-days: 30
