name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore IntranetDocumentos.csproj
        
      - name: Build main project
        run: dotnet build IntranetDocumentos.csproj --no-restore
        
      - name: Restore test dependencies
        run: dotnet restore Tests/IntranetDocumentos.Tests.csproj
        
      - name: Build tests
        run: dotnet build Tests/IntranetDocumentos.Tests.csproj --no-restore
        
      - name: Run tests
        run: dotnet test Tests/IntranetDocumentos.Tests.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./Tests/TestResults/*/coverage.cobertura.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      - name: Restore dependencies
        run: dotnet restore IntranetDocumentos.csproj
        
      - name: Build main project
        run: dotnet build IntranetDocumentos.csproj --no-restore
        
      - name: Publish
        run: dotnet publish IntranetDocumentos.csproj --no-build --configuration Release --output ./publish
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish/

  security:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      
      - name: Run security audit
        run: dotnet list mc_web_app.sln package --vulnerable --include-transitive
        
      - name: Check for outdated packages
        run: dotnet list mc_web_app.sln package --outdated
